module.exports.GENERAL = {
  SUCCESS: 200,
  ERROR: -200,
  NOT_AUTHENTICATED: 400
};

module.exports.ITEM = {
  LOADING_ERROR: 300,
  ADDING_ERROR: 301,
  UPDATING_ERROR: 302,
  DELETING_ERROR: 303
};

module.exports.ORDER = {
  STATUS_PENDING: 99,
  STATUS_ACCEPTED: 100,
  STATUS_DELIVERING: 101,
  STATUS_COMPLETED: 102,
  STATUS_CANCELED: -100
};